sudo: required

language: node_js

services:
  - docker

node_js:
  - "6"
  #- "5"
before_install:
  #- export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
install:
  - npm install
  - npm run compile:tsc # compile all the files

  - cd demo/
  # Install the demo app deps
  - npm install
   # Build the demo app
  - node_modules/.bin/ng build --prod
  # Start the docker container that serves the example app
  - docker run --name ng2psDemo -v dist/:/usr/share/nginx/html:ro -d -p 127.0.0.1:4200:80 nginx
  - sleep 10 # give the server a jump start
  - cd ../
script:
  # Execute the tests
  - npm test
after_script:
  - docker stop ng2psDemo
  - docker rm ng2psDemo
