language: node_js
node_js:
  - "6"
  - "5"
before_install:
  #- export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
install:
  - npm install
  - npm run demo &
  - sleep 15 # give the demo server a jump start
script:
  - npm test
after_script:
  - kill $(lsof -i:4200 | grep node | awk '{print $2}') # Kill the demo app process
